### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by wbolster** [snide/sphinx_rtd_theme#109]
The current templates unconditionally load modernizr from a cdn, and include a css file generated by `fonts.googleapis.com`. This means documentation pages will not finish loading (waiting for a dns timeout in some networks) if there is no network connectivity.

Would it be possible to add a configuration option to avoid this? For modernizr, I guess embedding is an option. For the fonts, I guess simply omitting it would be fine.

**Comment by agjohnson** [comment]
This looks to be resolved, closing.
