### ISSUE TITLE
sticky_navigation  not working with Chrome

### ISSUE THREAD

**Issue by pdion891** [snide/sphinx_rtd_theme#126]
The conf.py param:

``` python
        html_theme_options = {'sticky_navigation' : True}
```

Does not work with Chrome Browser. Also, the sticky_navigation does not seams to work with all section of a project on readthedocs.org, please refer to http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/latest/management.html

**Comment by heistermann** [comment]
I am trying to use the ``sphinx_rtd_theme`` for building my documentation locally and also found that the navigation bar could not be fixed to the top even with rather short left menus.

I set up my conf.py with the following lines:

```python
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_theme_options = {'sticky_navigation' : True}
``` 

but the navigation bar is still disappearing in heaven when I scroll down. 

I also experimented with the source in the site-packages directory. I manipulated `site-packages/sphinx_rtd_theme/theme.conf` and directly set `sticky_navigation = True`, but no effect.

Then I manipulated `site-packages/sphinx_rtd_theme/static/js/theme.js` and replaced the line 

`navBar.removeClass(stickyNavCssClass);` 

with 

`navBar.addClass(stickyNavCssClass);` 

as shown here:

```javascript
window.SphinxRtdTheme = (function (jquery) {
    var stickyNav = (function () {
        var navBar,
            win,
            stickyNavCssClass = 'stickynav',
            applyStickNav = function () {
                if (navBar.height() <= win.height()) {
                    navBar.addClass(stickyNavCssClass);
                } else {
                    //navBar.removeClass(stickyNavCssClass);
					navBar.addClass(stickyNavCssClass);
                }
            },
            enable = function () {
                applyStickNav();
                win.on('resize', applyStickNav);
            },
            init = function () {
                navBar = jquery('nav.wy-nav-side:first');
                win    = jquery(window);
            };
        jquery(init);
        return {
            enable : enable
        };
    }());
    return {
        StickyNav : stickyNav
    };
}($));
```
but without effects.

Please forgive me these amateurish attempts, I was just trying to figure out the reason for this behaviour. Do you have an idea how I could still fix the navigation bar to the top?

You can see a test version of the corresponding docs on http://heisterm.bitbucket.org.

**Comment by heistermann** [comment]
Updating from Sphinx 1.1 to 1.3 solved the problem. Sorry for bothering!

**Comment by Blendify** [comment]
Someone please close this.
