### ISSUE TITLE
Badge fills screen on smaller devices

### ISSUE THREAD

**Issue by jackwilsdon** [snide/sphinx_rtd_theme#144]
This issue is caused by `width: 100%` applied to the `img`. This can be found on [line 90](https://github.com/snide/sphinx_rtd_theme/blob/master/sass/_theme_badge.sass#L90) of [_theme_badge.sass](https://github.com/snide/sphinx_rtd_theme/blob/master/sass/_theme_badge.sass). Removing this line resolves the issue.

![An image of the problem](http://i.imgur.com/hFTELN0.png)

**Comment by rmzelle** [comment]
I'm running into the same issue with a small icon that is blown up:

![image](https://cloud.githubusercontent.com/assets/77951/6625967/e464e116-c8c9-11e4-8dd7-fa5963dca555.png)
(screenshot from http://dev-csl.readthedocs.org/en/latest/primer.html)

Inspecting the element shows (from sphinx_rtd_theme.css):

```
@media screen and (max-width: 768px)
img {
width: 100%;
height: auto;
}
```

**Comment by rmzelle** [comment]
Maybe it would suffice to change "width: 100%;" to "max-width: 100%;"?

**Comment by encukou** [comment]
`https://media.readthedocs.org/css/badge_only.css` seems to be inserted automatically in every page RTD serves, even on pages that use a different theme. The style stretches to all `img` on small devices.

Could RTD use a CSS class here to target only images in rst content? (or is this rule meant to target something else?)

**Comment by agjohnson** [comment]
@rmzelle I believe this approach is the most correct

@encukou Also this. A selector of `img` is too broad. Targeting `img` elements from rST should be trivial

**Comment by Blendify** [comment]
This has been fixed in https://github.com/snide/sphinx_rtd_theme/commit/20747b655171cc26e9770da950f2e62db12281e9 someone please close this.
