### ISSUE TITLE
Class attribute documentation is not shown

### ISSUE THREAD

**Issue by wbolster** [snide/sphinx_rtd_theme#158]
It appears the theme does not render documentation at all for class instance attributes, making it rather useless for documenting "struct"-like classes.

Example: http://temporenc.readthedocs.org/en/latest/#temporenc.Value  (locally generated version using the default Sphinx theme works fine)

It looks like this is the issue reported at rtfd/readthedocs.org#632  (which points to this repo, but I couldn't find a previously filed ticket...)

**Comment by whit537** [comment]
[Ditto](https://github.com/rtfd/readthedocs.org/issues/632#issuecomment-130363243).

**Comment by agjohnson** [comment]
Closing this issue here as it seems it has moved on to rtfd/readthedocs.org#632

**Comment by whit537** [comment]
Currently at https://github.com/sphinx-doc/sphinx/issues/2006, but yes, moved on from here, at least. :-)
