### ISSUE TITLE
small problem with image margin bottoms

### ISSUE THREAD

**Issue by kinkerl** [snide/sphinx_rtd_theme#159]
where is a small annoyance when using third party extensions for images and this theme. The problem is in 'sass/_theme_rst.sass' line 28

```
  // Usually it's a good idea to give images some space.
  .section > img
    margin-bottom: $base-line-height
```

This applies to:

```
<div class="section">
   <img>
</div>
```

For example, i wanted to use "https://github.com/spinus/sphinxcontrib-images" and it introduced an "a" tag in the tree:

```
<div class="section">
   <a>
      <img>
   </a>
</div>
```

Now the CSS is not applied and it looks different. 
The ">" is the problem. Why is that there? Would it be ok if we remove the ">" to allow a little more room for extensions?

Thanks

**Comment by Blendify** [comment]
This has been fixed in https://github.com/snide/sphinx_rtd_theme/commit/abaf44fe0b0f10e69abb5688eaec8db80f8c7440 please close @ericholscher
