### ISSUE TITLE
Compatibility with Sphinx 1.3

### ISSUE THREAD

**Issue by mhils** [snide/sphinx_rtd_theme#175]
Hi there,

thanks for the awesome template you're providing! I just upgrade to Sphinx 1.3 and noticed a few issues with the styling. Here's what I got on 1.2.3:
![](https://maximilianhils.com/upload/2015-03/2015-03-11_22-06-44.png)
![](https://maximilianhils.com/upload/2015-03/2015-03-11_22-07-31.png)

-------

And this is what I get on 1.3:
![](https://maximilianhils.com/upload/2015-03/2015-03-11_22-05-29.png)
![](https://maximilianhils.com/upload/2015-03/2015-03-11_22-06-03.png)

Apparently they changed the markup. It would be great if sphinx_rtd_theme would support the new one as well (or only the new one). :smiley:

**Comment by ericholscher** [comment]
Thanks for the report. We'll try and get this fixed up soon.

**Comment by bouzafr** [comment]
Is this patch on version 0.1.7 or not yet available?

**Comment by agjohnson** [comment]
@bouzafr if you are referring to the referenced commits, it is now released as 0.1.8

**Comment by bouzafr** [comment]
@agjohnson thx! all looks good now.
