### ISSUE TITLE
Local URIs for fonts/JS?

### ISSUE THREAD

**Issue by estan** [snide/sphinx_rtd_theme#184]
Hi,

I'm using sphinx-rtd-theme 0.1.7. In the generated HTML I get

    <link href='https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Roboto+Slab:400,700|Inconsolata:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

and

    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js"></script>

, effectively making the docs useful only when online. Is there any way to make the theme put those files locally in `_static` or so?

**Comment by agjohnson** [comment]
I believe this is resolved in part by #143, among others. Closing this
