### ISSUE TITLE
accesskey for next, previous links

### ISSUE THREAD

**Issue by mblakele** [snide/sphinx_rtd_theme#186]
cf https://github.com/rtfd/readthedocs.org/issues/1136

It would be nice to have an accesskey="n" and accesskey="p" attribute on the next and previous links in the page footer and pagination widgets. This should improve accessibility without breaking any current behavior.

**Comment by ericholscher** [comment]
Happy to merge this if you send a PR

**Comment by mblakele** [comment]
Thanks, but I think you already did: https://github.com/snide/sphinx_rtd_theme/pull/187

Closing: please reopen if there are any loose ends.
