### ISSUE TITLE
Relaxing sphinx requirement

### ISSUE THREAD

**Issue by jakirkham** [snide/sphinx_rtd_theme#189]
I know this may come across as a strange request, but is there a way of relaxing and/or removing the sphinx requirement. This is causing some of us build trouble with sphinx ( https://github.com/sphinx-doc/sphinx/issues/1845 ).

**Comment by agjohnson** [comment]
This might not be too far fetched, I don't know of anything requiring us to specify sphinx as a dependency. This would be worth exploring and possibly removing the requirement.

**Comment by birkenfeld** [comment]
It's probably the most pragmatic way out of this circular dependency (which shouldn't cause problems, but apparently too many build tool authors are unaware of the distinction between build-time and run-time dependencies).
