### ISSUE TITLE
Nested toctree as on readthedocs.org

### ISSUE THREAD

**Issue by PhilReinhold** [snide/sphinx_rtd_theme#198]
It appears that readthedocs.org uses a style which supports toctrees with depth greater than two

![screen shot 2015-05-20 at 10 57 43 am](https://cloud.githubusercontent.com/assets/1217560/7728781/334a3088-fedf-11e4-86b1-5e6813e8d8c0.png)

https://docs.readthedocs.org/en/latest/builds.html#sphinx

Is there some way of enabling this style of toctree with sphinx_rtd_theme?

**Comment by agjohnson** [comment]
This project is what RTD uses for it's theme. I implemented the multiple nav levels here already and brought the new theme into RTD

**Comment by ericholscher** [comment]
Yea, this is committed to the theme currently. Closing this.
