### ISSUE TITLE
RTD Mobile view not showing index

### ISSUE THREAD

**Issue by shravantc** [snide/sphinx_rtd_theme#199]
The mobile view does not show a index drop down on top left corner.

find the attached image 
![screenshot from 2015-05-22 15 31 56](https://cloud.githubusercontent.com/assets/10970993/7768335/c1aa34ae-0097-11e5-92cc-b5ff3e0d5a6d.png)

**Comment by agjohnson** [comment]
This seems to be an issue with the mkdocs theme. I notice the same issue at mkdocs.readthedocs.org. I'd raise the issue with the mkdocs project.

**Comment by shravantc** [comment]
Thank you @agjohnson . Raised the issue with mkdocs project.
