### ISSUE TITLE
Navbar scrollbar intermittently shows

### ISSUE THREAD

**Issue by agjohnson** [snide/sphinx_rtd_theme#200]
Moving rtfd/readthedocs.org#1276 here

I've also noticed a scrollbar on the nav intermittently -- only on an external display 50% of the time on OSX + Chrome/Safari. Report above was on Linux + FF38 of the same.

![2015-05-19-183004_310x784_scrot](https://cloud.githubusercontent.com/assets/837573/7708327/23293396-fe55-11e4-8ae3-b38b9501d62a.png)

**Comment by takluyver** [comment]
I've also just noticed this and gone to make a patch, but I was doing the same thing as #206.

It would be good to get some kind of fix in. If it's going to take longer to review a more complex approach like #215, maybe it's worth doing something like #206 as a stopgap measure. As I understand it, that would reduce the issue to only showing the unwanted scrollbar when the sidebar content is actually long enough to overflow the visible area.

**Comment by agjohnson** [comment]
I'm -1 on getting a release together with #206, #215 should be reviewed shortly.

You can always reference the branch directly if you wish to test out the fix immediately.
