### ISSUE TITLE
In-line code appears in black, rather than red

### ISSUE THREAD

**Issue by adam-vioozer** [snide/sphinx_rtd_theme#203]
Hi,

In version 0.1.18, inline code blocks like:

    Here comes an ``inline code block`` within a sentence

Appear in black, rather than the 0.1.17 red color:

![screen shot 2015-06-01 at 18 02 35](https://cloud.githubusercontent.com/assets/6304466/7915771/71b880b0-0888-11e5-8f81-e1ca8af5f473.png)
![screen shot 2015-06-01 at 18 02 47](https://cloud.githubusercontent.com/assets/6304466/7915770/71b77580-0888-11e5-83dd-e9693f47f20a.png)

I would like to argue that inline code is more readable when its color is different than the text color. Do you think you could revert back to the 0.1.17 red, or at least make this color configurable, please?

Thanks!

**Comment by agjohnson** [comment]
Can you provide a link to where this is happening? The color wasn't changed, the underlying html was changed by sphinx 1.3 -- we need to compensate in the css for the change.

**Comment by adam-vioozer** [comment]
Happens all around the file. For example, this line changed its color:

    #. Add ``#import "mtSDK.h"`` to your ``.pch`` file.

**Comment by agjohnson** [comment]
I actually cannot pin point *where* this would have changed. Testing doc builds with Sphinx 1.2.3 and sphinx_rtd_theme 0.1.7, I don't get red code blocks. The color comes from wyrm's code block definition, where the code is set with `color: $text-code-color`. We are overriding with `color: $black`, but as far as I can tell, that hasn't changed. This was maybe a RTD specific override that we might have removed recently? Again, not finding that either.
