### ISSUE TITLE
Missing modernizr.min.js

### ISSUE THREAD

**Issue by radarhere** [snide/sphinx_rtd_theme#213]
Hi. When modernizr.js is included, it is referred to with `<script src="_static/js/modernizr.min.js"></script>`. Because the path is relative rather than absolute, the file loads correctly on http://pillow.readthedocs.org/ but not http://pillow.readthedocs.org/releasenotes/index.html

Is the solution to just add a `/` before each reference to `_static` in https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html?

Thanks for the theme!

**Comment by cognifloyd** [comment]
Fixed in #195, but not yet released to pypi yet.

**Comment by radarhere** [comment]
Ah, okay, thanks very much. Apologies for the duplicate request.
