### ISSUE TITLE
Cyclic dependency with Sphinx 1.3.1

### ISSUE THREAD

**Issue by bjodah** [snide/sphinx_rtd_theme#232]
`sphinx_rtd_theme` 0.1.8 depends on `Sphinx` 1.3.1 and `Sphinx` 1.3.1 depends on `sphinx_rtd_theme>=0.1,<0.2`

For an offline install where I have downloaded all the `.tar.gz` files in advance this causes a download from PyPI no matter if I install `Sphinx` or `sphinx_rtd_theme` first. I realize it's not a major issue. I just patched `requirements.txt` in `sphinx_rtd_theme` to be empty.

**Comment by agjohnson** [comment]
This is related to #189. We might just remove the Sphinx requirement entirely. I'm not sure yet of the repercussions, so haven't made this change yet. I'll close this out as a duplicate and address the issue against #189 if we do.
