### ISSUE TITLE
Broken edit links for module sources

### ISSUE THREAD

**Issue by bdarnell** [snide/sphinx_rtd_theme#237]
The "Edit on github" links for pages like http://www.tornadoweb.org/en/stable/_modules/tornado/stack_context.html are broken; they point to a non-existent `.rst` file. Is it possible to suppress the edit link for these pages (or ideally point it to the real source)?

**Comment by agjohnson** [comment]
This seems to be an issue with rtfd/readthedocs.org, can you reopen the issue there?

Specifically, it appears we are passing in a different slug from our `conf.py` overrides and in the footer api request.
