### ISSUE TITLE
Increase code sample vertical padding a bit

### ISSUE THREAD

**Issue by psss** [snide/sphinx_rtd_theme#242]
Thanks for the RTD theme, it's really beautiful! There's just the
only thing which does not please my eyes: The vertical padding for
code samples is currently set to 0 which results in the text being
completely pushed to the border. No space for breathing.

    <code class="docutils literal"><span class="pre">conf.py</span></code>

I would suggest to increase the padding from current `0px 5px` to
`2px 5px`. This would make the command line options and similar
stuff a bit more readable when rendered as html page. Thanks.

**Comment by agjohnson** [comment]
I think this is a fine idea, it does seem a bit cramped. I'll put together a PR, I'm in the process of rolling up a release.

**Comment by psss** [comment]
Great! Thank you.
