### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by agjohnson** [snide/sphinx_rtd_theme#244]
I'd prefer to follow semantic versioning, making the next release -- with backwards incompatible changes -- v0.2. In preparing a release though, I remembered that Sphinx pinned `sphinx_rtd_theme>0.1<0.2`. This means that until we can get sphinx to bump this on future releases, users will get the 0.1.x series unless they specifically install 0.2.

Unless anyone has any thoughts here, I am going to continue preparing the next release as 0.1.9. We'll want to open up this discussion with Sphinx core however, as the version decision seems to have been arbitrary.

**Comment by agjohnson** [comment]
cc @ericholscher

**Comment by ericholscher** [comment]
I'm fine with bumping the version to .2 -- We can move forward and folks can explicitly install if it they want.

**Comment by ericholscher** [comment]
Also happy to call it 1.0 if we're going with real semvar.

**Comment by agjohnson** [comment]
Aye, might as well follow semver strictly and go 1.x if we do. +1 on that

My concern is folks installing sphinx locally likely won't know to do this and will get a theme with some slightly broken pieces, which would be bad experience on our part.

Thinking about this more, I'd be more concerned about that use case than about folks that have forked/extended the theme, and have custom css rules that would be invalidated by the additional html element -- this footprint would be considerably smaller, maybe not even existent.

Unfortunately, I think the wisest solution here is to continue with our current scheme and communicate to sphinx that we need the version restriction relaxed for their next release.

**Comment by agjohnson** [comment]
I've opened a PR on sphinx that relaxes the versioning scheme.

**Comment by agjohnson** [comment]
And merged, looks Sphinx will target <2.0 after the 1.3.2 release is out. Next release for us can remain 0.1.9
