### ISSUE TITLE
Images become very large on narrow displays

### ISSUE THREAD

**Issue by ideasman42** [snide/sphinx_rtd_theme#246]
Using rtd 1.8x making a page very narrow will increase some image sizes considerably.
Originally reported here: https://developer.blender.org/T46079

Tested with the default theme and this problem doesn't happen.

See: 
http://www.blender.org/manual/render/opengl.html#rendering-an-animation-using-opengl-render

![a](https://cloud.githubusercontent.com/assets/1869379/9846568/4e10c15a-5b16-11e5-8d5e-9acfd2c5b38d.png)

![b](https://cloud.githubusercontent.com/assets/1869379/9846566/4a37c6fa-5b16-11e5-807c-7b0f0beb3bb5.png)

**Comment by zhanghongyi** [comment]
Same here, I have encountered a similar issue.

**Comment by Michael-Lazell** [comment]
I'm looking forward to this being fixed because I really need to put small pictures of buttons inline with text.

**Comment by jackwilsdon** [comment]
Sounds like this is the same as #144.

**Comment by ideasman42** [comment]
Yes, it's a duplicate of #144, closing.
