### ISSUE TITLE
Multiple not translated strings

### ISSUE THREAD

**Issue by Kern3l** [snide/sphinx_rtd_theme#260]
I'd like to have my docs translated to Polish and now I have to translate displayed strings myself. Examples from current master:

https://github.com/snide/sphinx_rtd_theme/blob/012d42db6a2b00f799223963fb8b0aa3754630eb/sphinx_rtd_theme/breadcrumbs.html
"Docs", "Edit on GitHub", "Edit on Bitbucket", "View page source"

I expected the template to honor 'language' setting from the configuration file.

**Comment by razor-1** [comment]
+1 for removal of all hardcoded strings.  Even 'Next' and 'Previous' in the footer are not translated.

**Comment by Blendify** [comment]
I think after https://github.com/snide/sphinx_rtd_theme/commit/e43226965eaf694551940cc7a0adae6b72bd8387 got merged this can now be closed. @ericholscher
