### ISSUE TITLE
Collapsible 

### ISSUE THREAD

**Issue by glenfant** [snide/sphinx_rtd_theme#270]
I can see that some Shinx sites that use this theme have a collapsible/expandable navigation tree in the sidebar. In example : http://builtoncement.com/2.6/ , but reading their conf.py and your doc, I didn't find the way to achieve this.

Thanks in advance for any hint.

**Comment by agjohnson** [comment]
The option for this theme is: 
https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/theme.conf#L10

**Comment by glenfant** [comment]
Oh thanks. This should be in the README IMHO.

**Comment by akien-mga** [comment]
Is this option exposed in `html_theme_options`? I tried using it this way but it did not seem to work so far: https://github.com/godotengine/godot-docs/commit/7647a7cf661d51456d802c785a2eb6d69667ac2a

Also, I agree with @glenfant that all configuration options of sphinx_rtd_theme should be featured in the README.rst. For [Godot Engine's docs](http://docs.godotengine.org) we've been considering forking the theme to be able to add this feature, but by chance I found this closed issue and notice that the option we wanted *might* exist already.

**Comment by akien-mga** [comment]
After having a quick look at the way it was implemented (ae6c09b and 5e40211), it seems there is indeed no way to toggle this option from `conf.py`, so we'll probably have to fork the theme to use it on RTD. I think many projects would be glad for an easy-to-change option though that wouldn't imply modifying the theme source files.

**Comment by agjohnson** [comment]
@akien-mga feel free to send a PR, not sure why this requires forking.

Agreed on documenting options, we don't have this written down anywhere.

**Comment by akien-mga** [comment]
I meant that it requires forking for our own usage so that we can change the settings, not to develop it in parallel. If the default value was set to False in 5e40211, I guess it means that you don't want it set to True, so such a PR from us would not be accepted.

Of course I could make a PR to expose the setting, but I don't have the knowledge for that :)
