### ISSUE TITLE
html_theme_options

### ISSUE THREAD

**Issue by nikohansen** [snide/sphinx_rtd_theme#281]
Where do I find the available `html_theme_options`?

**Comment by muuki88** [comment]
You can take a look at the [theme.conf](https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/theme.conf) file

**Comment by Vorlif** [comment]
If I try `navigation_depth` I get the error:

```
Theme error:
unsupported theme option 'navigation_depth' given
```

Does anyone have a solution?
Thank you in advance.

**Comment by dmitriid** [comment]
- `navigation_depth`: unsupported theme option 'navigation_depth' given
- 'collapse_navigation': False — navigation is collapsed

**Comment by JoeyZwicker** [comment]
+1 I'm using this theme and it would be really helpful if `navigation_depth` was supported so I could manage sidebar navigation more easily. @snide @ericholscher.

**Comment by agjohnson** [comment]
`navigation_depth` is not in a release yet, you can use the repo address in a requirements file for now to get the option.

**Comment by sjezewski** [comment]
Thanks @agjohnson, but a few more questions about that --

That seems like it will enable us to use the new feature locally, but will it work when deploying via readthedocs?

I was under the impression that readthedocs has this theme builtin. Do we know if that version has this feature?

If not, I'm not sure how to use `conf.py` in a way that uses the latest code (as you suggest) when the readthedocs service builds the documentation. But, if there is a way to do that, that would be great.

[You can see our config here](https://github.com/pachyderm/pachyderm/blob/792ca0bd1c07ade154e8256afa14b562ff0f3a6c/doc/conf.py#L133)

**Comment by agjohnson** [comment]
@sjezewski you can install any python package you'd like using a requirements file, including a particular version of the theme

**Comment by sjezewski** [comment]
Ok great! Thanks for the help

**Comment by Blendify** [comment]
There is another task for theme options documentation. So this task can be closed @ericholscher
