### ISSUE TITLE
Would it be possible to integrate sphinx_rtd_theme to sphinx-doc 1.5?

### ISSUE THREAD

**Issue by nowox** [snide/sphinx_rtd_theme#293]
`sphinx_rtd_theme` is an awesome theme that worth to be part of `sphinx-doc`. Why is it still proposed as a separate theme?

**Comment by Blendify** [comment]
Please take this up with sphinx-doc instead. Someone please close.

**Comment by ericholscher** [comment]
Hmm. We could in fact ship it as part of Sphinx, but then we'd be stuck to the release cycle of the project. `alabaster` is now the default theme, and it shipped separately, so I think it makes sense to keep this theme installable as a separate module.
