### ISSUE TITLE
Maxdepth is a int, not a string.

### ISSUE THREAD

**Issue by Carreau** [snide/sphinx_rtd_theme#334]
https://github.com/snide/sphinx_rtd_theme/pull/309 seem to have make maxdepth a string ('4')  which make sphinx complain in python 3  that string and int are not-orderable.

**Comment by ncmaas** [comment]
Hey, I just ran into this problem as well. Would love to see the PR merged :)

Also, I think #323 may be a duplicate of the same issue.

Thanks!
