### ISSUE TITLE
Noob question on getting Github link to show up on page...

### ISSUE THREAD

**Issue by chrismarino** [snide/sphinx_rtd_theme#339]
Hi I'd like to use a variation of this RTD theme on my own hosted site. I've got most things up and looking OK, but I want to use the Edit on Github link in the breadcrumbs and I don't really know how to set that up. I saw that you can set page level meta data :github_url:  but could not get it to do anything.

So, some basic questions: Will this conf option work on a self hosted site?  I don't recall setting the github account info anywhere so thinking that this might only work on RTD.com??

If it will work, can you please provide an example of what/how to set the metadata?  I put the :github_url: directive in my .rst files, but not even sure that is how this is supposed to work.

**Comment by thiyagaraj** [comment]
Hi @chrismarino , add something like this to your conf.py

~~~
html_context = {
    # Enable the "Edit in GitHub link within the header of each page.
    'display_github': True,
    # Set the following variables to generate the resulting github URL for each page. 
    # Format Template: https://{{ github_host|default("github.com") }}/{{ github_user }}/{{ github_repo }}/blob/{{ github_version }}{{ conf_py_path }}{{ pagename }}{{ suffix }}
    'github_user': 'username',
    'github_repo': 'repo-name',
    'github_version': 'master/source/' 
}
~~~

**Comment by Blendify** [comment]
@ericholscher please close this
