### ISSUE TITLE
Search does not return results

### ISSUE THREAD

**Issue by wigging** [snide/sphinx_rtd_theme#348]
The search feature is not working, it continuously displays "Searching..." and never returns any results.  I installed the theme using `pip` and made the appropriate edits in the `conf.py` file.  I'm using the latest version of Sphinx to build the html.  The search feature works fine when I use a default Sphinx theme.

![sphinx-search](https://cloud.githubusercontent.com/assets/6828967/21202595/fd2acb68-c21c-11e6-8078-0cfb3e840a19.gif)

**Comment by wigging** [comment]
Apparently the pip installation approach did not install all the necessary files.  So I manually downloaded all the files and edited the conf.py accordingly and now everything works.

In summary, search does not work when installing via pip:

```python
# Install theme via $ pip install sphinx_rtd_theme
# In conf.py add the following
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

Manually downloading and installing the theme allows search to work correctly:

```python
# Download theme from GitHub then place sphinx_rtd_theme folder into _themes directory
# In conf.py add the following
html_theme = "sphinx_rtd_theme"
html_theme_path = ["_themes", ]
```

**Comment by Blendify** [comment]
This was a bug that was fixed recently and is an issue with running the theme with Sphinx 1.5.X. To get this to work with the pip file  use:

`git+https://github.com/snide/sphinx_rtd_theme@abfa98539a2bfc44198a9ca8c2f16efe84cc4d26`

**Comment by wigging** [comment]
The installation instructions in the README should be updated for Sphinx 1.5

**Comment by Blendify** [comment]
I think this issue can be closed now.

**Comment by fhennecker** [comment]
I'm experiencing the same issue here and have tried several options (including installing manually by git cloning the theme).

I have an error in the Chrome console:

```
Uncaught TypeError: Search.loadIndex is not a function
    at HTMLDocument.<anonymous>
```

Using `python 3.7.1`, `sphinx 2.0.0`, `sphinx-rtd-theme==0.4.3 `
Any ideas?

**Comment by Blendify** [comment]
@fhennecker #728 might be a fix.

**Comment by fhennecker** [comment]
I tried your commit by installing using pip with the following command:
```
pip install git+https://github.com/snide/sphinx_rtd_theme@bd98133
```
The same issue occurs

**Comment by Blendify** [comment]
Can you please open a new issue.

**Comment by BijanSeif** [comment]
> ```python
> html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
> ```

Hi everyone
My problem solved just by eliminating the following code line:
`html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]`
