### ISSUE TITLE
Newbie question on adding extra content to footer

### ISSUE THREAD

**Issue by HTenkanen** [snide/sphinx_rtd_theme#349]
Hi, I'd like to add extra content to the footer of my [website](https://autogis.github.io) but don't quite know  how to do it. I know there is the *extrafooter* block in footer.html ([discussed here](https://github.com/snide/sphinx_rtd_theme/pull/241)) but how can I add stuff to that from conf.py?

I would just love to add couple of Licence logos (CC 4.0 BY-SA and GPLv3) to the footer and have been searching for a solution to achieve that. Thanks, in advance!

**Comment by christianspecht** [comment]
[This page](http://www.sphinx-doc.org/en/latest/templating.html?highlight=template#jinja-sphinx-templating-primer) in the Sphinx docs explains how to add stuff to an existing block.

For the `extrafooter` block, you need to put a new HTML file into your `templates_path` (usually `/_templates`), with the following content:

    {% extends "!footer.html" %}
    {% block extrafooter %}
        <p><a href="http://foo">new example link</a></p>
        {{ super() }}
    {% endblock %}


[Here's an example from a project of mine](https://github.com/christianspecht/scm-backup-docs/commit/2cc308493f75726956efe80f13157a7cfb32dc35).

**Comment by Blendify** [comment]
Please close this @ericholscher
