### ISSUE TITLE
Question about current tagged alpha version

### ISSUE THREAD

**Issue by alexwidener** [snide/sphinx_rtd_theme#353]
Hi! 

I'm implementing this theme into a documentation build environment and noticed that you have a PR in master and not in 0.1.10-alpha, which is PR #345 

It's awesome that this is in master, but as it's added to the v0.1.10 milestone, I was curious when it might be implemented into the v.0.1.10-alpha tag? Normally at home, I'd just use master, but my production environment is based solely off of tagged versions. 

Thanks for the awesome work!

**Comment by Blendify** [comment]
Please close this @ericholscher

**Comment by alexwidener** [comment]
Has it been addressed, @Blendify ?

**Comment by alexwidener** [comment]
It looks like yes, this has been addressed and is included in the tag of 0.2.0

I'll go ahead and close it.
