### ISSUE TITLE
release updates to breadcrumbs.html

### ISSUE THREAD

**Issue by delgadom** [snide/sphinx_rtd_theme#361]
Currently deployed version fails to build if meta not set. This is fixed in master. A deploy would be great!

In master [`sphinx_rtd_theme/breadcrumbs.html`: 9-15]:
```html
{% if meta is defined and meta is not none %}
{% set check_meta = True %}
{% else %}
{% set check_meta = False %}
{% endif %}

{% if check_meta and 'github_url' in meta %}
```

On `0.1.10-alpha` [`sphinx_rtd_theme/breadcrumbs.html`: 13]:
```html
{% if meta is defined and 'github_url' in meta %}
```

See also rtfd/readthedocs.org#2590

**Comment by ericholscher** [comment]
I've just released 0.2.0
