### ISSUE TITLE
How to remove ethical ad from Sphinx theme?

### ISSUE THREAD

**Issue by rameshthoomu** [snide/sphinx_rtd_theme#362]
I have a requirement to remove ethical ad from sphinx theme? Is there any easy way to do this?
![capture](https://cloud.githubusercontent.com/assets/17034502/23150320/b9d99928-f7c0-11e6-8d42-e58909fe85c6.PNG)

**Comment by kyrias** [comment]
If you don't want ads on the hosted service, either pay for the hosted service, contribute to RTD, or host the docs yourself.  This issue isn't with the theme itself.

**Comment by ericholscher** [comment]
Yep, as noted this is not an issue with the theme.

**Comment by polyzen** [comment]
https://docs.readthedocs.io/en/latest/ethical-advertising.html
