### ISSUE TITLE
v0.2.1 broke `toctree` for a few pages

### ISSUE THREAD

**Issue by ivankravets** [snide/sphinx_rtd_theme#369]
* http://docs.platformio.org/en/latest/frameworks/index.html
* https://github.com/platformio/platformio-docs/blob/develop/frameworks/index.rst
* http://docs.platformio.org/en/latest/core.html
* https://github.com/platformio/platformio-docs/blob/develop/core.rst

Tired locally v0.2.0 and it works correctly. Is possible to force ReadTheDocs to use v0.2.0?
I know that is possible to pre-install custom pip-deps but ReadTheDocs uses own `sphinx_rtd_theme` and doesn't allow to use other.

Thanks!

**Comment by agjohnson** [comment]
Does specifying `sphinx_rtd_theme==0.2.0` in a requirements file not work? This should work for overriding our default versions.

I'll see about poking the 0.2.1 bugfix with your project.

**Comment by agjohnson** [comment]
Acutally, nevermind. I think 0.2.0 hosed your build, 0.2.1 seems to be okay after wiping out your virtualenv. Look better now?

**Comment by ericholscher** [comment]
This was indeed a bug in 0.2.1, I've deployed 0.2.2 to fix it.

**Comment by ivankravets** [comment]
Thanks, it works now with 0.2.2.

P.S: Thanks a lot for RTD 👍 😊
